#!/bin/bash
#####################################################
#
#  POD - Processing On Demand open source platform
#
#####################################################
#
#  Command Line Interface
#
#####################################################

if [[ $# == 0 ]]; then
	./print --help
    exit
fi

if [[ $1 == '--help' ]]; then
    ./print --help
    exit
fi

if [[ -z $POD_URL ]]; then
	echo "Environment variable POD_URL has no value. Please set it up"
	echo "It must contain the URL to the manager"
	exit
fi

if [[ $1 == 'newExecution' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=newExecution&name=$2" | json_pp
		exit
	fi
	if [[ $# == 3 ]] && [[ -n $2 ]] && [[ -n $3 ]] ; then
		curl "$POD_URL/?action=newExecution&name=$2&input=$3" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "newExecution --help"
		exit
	else 
		echo "Usage: pod newExecution name"
		echo "Type pod newExecution --help for more information"
		exit
	fi
fi


if [[ $1 == 'getExecutionStatus' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=getExecutionStatus&executionId=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "getExecutionStatus --help"
		exit
	else 
		echo "Usage: pod getExecutionStatus name"
		echo "Type pod getExecutionStatus --help for more information"
		exit
	fi
fi

if [[ $1 == 'newActivity' ]]; then

	if [[ $# == 3 ]] && [[ -n $2 ]] && [[ -n $3 ]]; then
		curl "$POD_URL/?action=newActivity&installationScriptLocation=$3&name=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "newActivity --help"
		exit
	else 
		echo "Usage: pod newActivity name installationScriptLocation"
		echo "Type pod newActivity --help for more information"
		exit
	fi
fi


if [[ $1 == 'getActivityStatus' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=getActivityStatus&name=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "getActivityStatus --help"
		exit
	else 
		echo "Usage: pod getActivityStatus name"
		echo "Type pod getActivityStatus --help for more information"
		exit
	fi
fi

if [[ $1 == 'deleteActivity' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=deleteActivity&name=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "deleteActivity --help"
		exit
	else 
		echo "Usage: pod deleteActivity name"
		echo "Type pod deleteActivity --help for more information"
		exit
	fi
fi


if [[ $1 == 'terminateExecution' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=terminateExecution&executionId=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "terminateExecution --help"
		exit
	else 
		echo "Usage: pod terminateExecution name"
		echo "Type pod terminateExecution --help for more information"
		exit
	fi
fi

if [[ $1 == 'newPolicy' ]]; then

	if [[ $# == 3 ]] && [[ -n $2 ]] && [[ -n $3 ]]; then
		curl "$POD_URL/?action=newPolicy&name=$2&rules=$3" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "newPolicy --help"
		exit
	else 
		echo "Usage: pod newPolicy name rules"
		echo "Rules have the structure rule1=value1,rule2=value2"
		echo "Type pod newPolicy --help for more information"
		exit
	fi
fi

if [[ $1 == 'applyPolicy' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=applyPolicy&name=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "applyPolicy --help"
		exit
	else 
		echo "Usage: pod applyPolicy name"
		echo "Type pod applyPolicy --help for more information"
		exit
	fi
fi


if [[ $1 == 'deletePolicy' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=deletePolicy&name=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "deletePolicy --help"
		exit
	else 
		echo "Usage: pod deletePolicy name"
		echo "Type pod deletePolicy --help for more information"
		exit
	fi
fi


if [[ $1 == 'viewActivePolicy' ]]; then

	if [[ $# == 1 ]] ; then
		curl "$POD_URL/?action=viewActivePolicy" | json_pp
		exit
	fi
	
	if [[ $# == 2 ]] && [[ $2 == '--help' ]]; then
		./print "viewActivePolicy --help"
		exit
	else 
		echo "Usage: pod viewActivePolicy"
		echo "Type pod viewActivePolicy --help for more information"
		exit
	fi
fi


if [[ $1 == 'resetPolicies' ]]; then

	if [[ $# == 1 ]] ; then
		curl "$POD_URL/?action=resetPolicies" | json_pp
		exit
	fi
	
	if [[ $# == 2 ]] && [[ $2 == '--help' ]]; then
		./print "resetPolicies --help"
		exit
	else 
		echo "Usage: pod resetPolicies"
		echo "Type pod resetPolicies --help for more information"
		exit
	fi
fi



if [[ $1 == 'getPolicies' ]]; then

	if [[ $# == 1 ]] ; then
		curl "$POD_URL/?action=getPolicies" | json_pp
		exit
	fi
	
	if [[ $# == 2 ]] && [[ $2 == '--help' ]]; then
		./print "getPolicies --help"
		exit
	else 
		echo "Usage: pod getPolicies"
		echo "Type pod getPolicies --help for more information"
		exit
	fi
fi

if [[ $1 == 'getWorkers' ]]; then

	if [[ $# == 1 ]] ; then
		curl "$POD_URL/?action=getWorkers" | json_pp
		exit
	fi
	
	if [[ $# == 2 ]] && [[ $2 == '--help' ]]; then
		./print "getWorkers --help"
		exit
	else 
		echo "Usage: pod getWorkers"
		echo "Type pod getWorkers --help for more information"
		exit
	fi
fi

if [[ $1 == 'logs' ]]; then

	if [[ $# == 2 ]] && [[ -n $2 ]] && [[ $2 != '--help' ]] ; then
		curl "$POD_URL/?action=logs&name=$2" | json_pp
		exit
	fi
	
	if [[ $2 == '--help' ]]; then
		./print "logs type --help"
		exit
	else 
		echo "Usage: pod logs type"
		echo "Type pod logs --help for more information"
		exit
	fi
fi

echo "Unknown command. Use --help to get indications"
exit
